parameters:
  epochs: 20
  batch_size: 8       #8


artifacts:
  artifacts_dir: artifacts
  model_dir: models
  plots_dir: plots
  model_name: model.h5
  CHECKPOINT_DIR: checkpoints



log:
  log_dir: logs_dir
  general_logs: general_log
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs